export const USUARIOS_TEST_ONE: any = [
  {
    id: 1,
    name: 'Juan Pérez',
    email: 'juan.perez@empresa.com',
    role: 'developer',
    status: 'active',
    joinDate: new Date('2023-01-15'),
    salary: 75000,
    department: 'Engineering',
  },
  {
    id: 2,
    name: 'María García',
    email: 'maria.garcia@empresa.com',
    role: 'designer',
    status: 'active',
    joinDate: new Date('2023-03-20'),
    salary: 68000,
    department: 'Design',
  },
  {
    id: 3,
    name: 'Carlos López',
    email: 'carlos.lopez@empresa.com',
    role: 'manager',
    status: 'active',
    joinDate: new Date('2022-11-10'),
    salary: 95000,
    department: 'Management',
  },
  {
    id: 4,
    name: 'Ana Martínez',
    email: 'ana.martinez@empresa.com',
    role: 'developer',
    status: 'pending',
    joinDate: new Date('2024-01-05'),
    salary: 72000,
    department: 'Engineering',
  },
  {
    id: 5,
    name: 'Luis Rodríguez',
    email: 'luis.rodriguez@empresa.com',
    role: 'admin',
    status: 'inactive',
    joinDate: new Date('2023-07-22'),
    salary: 85000,
    department: 'IT',
  },

  // --- DATA GENERADA ---
  {
    id: 6,
    name: 'Sofía Torres',
    email: 'sofia.torres@empresa.com',
    role: 'developer',
    status: 'active',
    joinDate: new Date('2022-09-12'),
    salary: 78000,
    department: 'Engineering',
  },
  {
    id: 7,
    name: 'Miguel Herrera',
    email: 'miguel.herrera@empresa.com',
    role: 'tester',
    status: 'active',
    joinDate: new Date('2023-02-08'),
    salary: 62000,
    department: 'QA',
  },
  {
    id: 8,
    name: 'Laura Gómez',
    email: 'laura.gomez@empresa.com',
    role: 'designer',
    status: 'active',
    joinDate: new Date('2021-11-30'),
    salary: 70000,
    department: 'Design',
  },
  {
    id: 9,
    name: 'Andrés Moreno',
    email: 'andres.moreno@empresa.com',
    role: 'developer',
    status: 'inactive',
    joinDate: new Date('2020-05-18'),
    salary: 80000,
    department: 'Engineering',
  },
  {
    id: 10,
    name: 'Valentina Ruiz',
    email: 'valentina.ruiz@empresa.com',
    role: 'hr',
    status: 'active',
    joinDate: new Date('2023-06-01'),
    salary: 65000,
    department: 'Human Resources',
  },
  {
    id: 11,
    name: 'Camilo Sánchez',
    email: 'camilo.sanchez@empresa.com',
    role: 'manager',
    status: 'active',
    joinDate: new Date('2019-03-14'),
    salary: 98000,
    department: 'Management',
  },
  {
    id: 12,
    name: 'Natalia Castro',
    email: 'natalia.castro@empresa.com',
    role: 'developer',
    status: 'pending',
    joinDate: new Date('2024-02-01'),
    salary: 73000,
    department: 'Engineering',
  },
  {
    id: 13,
    name: 'Diego Ramírez',
    email: 'diego.ramirez@empresa.com',
    role: 'support',
    status: 'active',
    joinDate: new Date('2022-08-19'),
    salary: 58000,
    department: 'Support',
  },
  {
    id: 14,
    name: 'Paula Jiménez',
    email: 'paula.jimenez@empresa.com',
    role: 'designer',
    status: 'inactive',
    joinDate: new Date('2021-01-25'),
    salary: 69000,
    department: 'Design',
  },
  {
    id: 15,
    name: 'Jorge Medina',
    email: 'jorge.medina@empresa.com',
    role: 'admin',
    status: 'active',
    joinDate: new Date('2020-10-10'),
    salary: 86000,
    department: 'IT',
  },
  {
    id: 16,
    name: 'Daniela Ortiz',
    email: 'daniela.ortiz@empresa.com',
    role: 'developer',
    status: 'active',
    joinDate: new Date('2022-04-07'),
    salary: 79000,
    department: 'Engineering',
  },
  {
    id: 17,
    name: 'Felipe Rojas',
    email: 'felipe.rojas@empresa.com',
    role: 'tester',
    status: 'pending',
    joinDate: new Date('2024-01-18'),
    salary: 60000,
    department: 'QA',
  },
  {
    id: 18,
    name: 'Juliana Pineda',
    email: 'juliana.pineda@empresa.com',
    role: 'support',
    status: 'active',
    joinDate: new Date('2023-09-03'),
    salary: 59000,
    department: 'Support',
  },
  {
    id: 19,
    name: 'Sebastián Vargas',
    email: 'sebastian.vargas@empresa.com',
    role: 'developer',
    status: 'inactive',
    joinDate: new Date('2021-06-22'),
    salary: 81000,
    department: 'Engineering',
  },
  {
    id: 20,
    name: 'Carolina Peña',
    email: 'carolina.pena@empresa.com',
    role: 'hr',
    status: 'active',
    joinDate: new Date('2022-12-05'),
    salary: 66000,
    department: 'Human Resources',
  },

  // hasta 40
  {
    id: 21,
    name: 'Ricardo León',
    email: 'ricardo.leon@empresa.com',
    role: 'manager',
    status: 'active',
    joinDate: new Date('2018-07-11'),
    salary: 102000,
    department: 'Management',
  },
  {
    id: 22,
    name: 'Tatiana Flores',
    email: 'tatiana.flores@empresa.com',
    role: 'designer',
    status: 'pending',
    joinDate: new Date('2024-01-29'),
    salary: 71000,
    department: 'Design',
  },
  {
    id: 23,
    name: 'Oscar Cárdenas',
    email: 'oscar.cardenas@empresa.com',
    role: 'developer',
    status: 'active',
    joinDate: new Date('2020-02-17'),
    salary: 84000,
    department: 'Engineering',
  },
  {
    id: 24,
    name: 'Mónica Duarte',
    email: 'monica.duarte@empresa.com',
    role: 'support',
    status: 'inactive',
    joinDate: new Date('2019-11-09'),
    salary: 57000,
    department: 'Support',
  },
  {
    id: 25,
    name: 'Alejandro Núñez',
    email: 'alejandro.nunez@empresa.com',
    role: 'admin',
    status: 'active',
    joinDate: new Date('2021-08-14'),
    salary: 88000,
    department: 'IT',
  },
  {
    id: 26,
    name: 'Isabella Muñoz',
    email: 'isabella.munoz@empresa.com',
    role: 'developer',
    status: 'active',
    joinDate: new Date('2022-03-28'),
    salary: 77000,
    department: 'Engineering',
  },
  {
    id: 27,
    name: 'Kevin Salazar',
    email: 'kevin.salazar@empresa.com',
    role: 'tester',
    status: 'inactive',
    joinDate: new Date('2020-12-01'),
    salary: 61000,
    department: 'QA',
  },
  {
    id: 28,
    name: 'Mariana Vélez',
    email: 'mariana.velez@empresa.com',
    role: 'designer',
    status: 'active',
    joinDate: new Date('2023-05-16'),
    salary: 72000,
    department: 'Design',
  },
  {
    id: 29,
    name: 'Esteban Gil',
    email: 'esteban.gil@empresa.com',
    role: 'developer',
    status: 'pending',
    joinDate: new Date('2024-02-10'),
    salary: 76000,
    department: 'Engineering',
  },
  {
    id: 30,
    name: 'Lorena Acosta',
    email: 'lorena.acosta@empresa.com',
    role: 'hr',
    status: 'active',
    joinDate: new Date('2021-04-21'),
    salary: 67000,
    department: 'Human Resources',
  },
  {
    id: 31,
    name: 'Héctor Molina',
    email: 'hector.molina@empresa.com',
    role: 'support',
    status: 'active',
    joinDate: new Date('2022-10-13'),
    salary: 60000,
    department: 'Support',
  },
  {
    id: 32,
    name: 'Viviana Ríos',
    email: 'viviana.rios@empresa.com',
    role: 'designer',
    status: 'inactive',
    joinDate: new Date('2019-06-30'),
    salary: 70500,
    department: 'Design',
  },
  {
    id: 33,
    name: 'Santiago Ospina',
    email: 'santiago.ospina@empresa.com',
    role: 'developer',
    status: 'active',
    joinDate: new Date('2023-08-04'),
    salary: 79000,
    department: 'Engineering',
  },
  {
    id: 34,
    name: 'Daniel Rincón',
    email: 'daniel.rincon@empresa.com',
    role: 'admin',
    status: 'active',
    joinDate: new Date('2020-01-19'),
    salary: 90000,
    department: 'IT',
  },
  {
    id: 35,
    name: 'Karen Salas',
    email: 'karen.salas@empresa.com',
    role: 'tester',
    status: 'pending',
    joinDate: new Date('2024-01-12'),
    salary: 63000,
    department: 'QA',
  },
  {
    id: 36,
    name: 'Mauricio Álvarez',
    email: 'mauricio.alvarez@empresa.com',
    role: 'manager',
    status: 'active',
    joinDate: new Date('2017-09-05'),
    salary: 105000,
    department: 'Management',
  },
  {
    id: 37,
    name: 'Claudia Fajardo',
    email: 'claudia.fajardo@empresa.com',
    role: 'hr',
    status: 'inactive',
    joinDate: new Date('2018-02-27'),
    salary: 64000,
    department: 'Human Resources',
  },
  {
    id: 38,
    name: 'Iván Cifuentes',
    email: 'ivan.cifuentes@empresa.com',
    role: 'support',
    status: 'active',
    joinDate: new Date('2023-11-11'),
    salary: 61000,
    department: 'Support',
  },
  {
    id: 39,
    name: 'Nataly Beltrán',
    email: 'nataly.beltran@empresa.com',
    role: 'designer',
    status: 'active',
    joinDate: new Date('2022-07-23'),
    salary: 73500,
    department: 'Design',
  },
  {
    id: 40,
    name: 'Brayan Pardo',
    email: 'brayan.pardo@empresa.com',
    role: 'developer',
    status: 'active',
    joinDate: new Date('2021-12-02'),
    salary: 82000,
    department: 'Engineering',
  },
  {
    id: 40,
    name: 'Brayan Pardo',
    email: 'brayan.pardo@empresa.com',
    role: 'developer',
    status: 'active',
    joinDate: new Date('2021-12-02'),
    salary: 82000,
    department: 'Engineering',
  },
  {
    id: 40,
    name: 'Brayan Pardo',
    email: 'brayan.pardo@empresa.com',
    role: 'developer',
    status: 'active',
    joinDate: new Date('2021-12-02'),
    salary: 82000,
    department: 'Engineering',
  },
  {
    id: 40,
    name: 'Brayan Pardo',
    email: 'brayan.pardo@empresa.com',
    role: 'developer',
    status: 'active',
    joinDate: new Date('2021-12-02'),
    salary: 82000,
    department: 'Engineering',
  },
  {
    id: 40,
    name: 'Brayan Pardo',
    email: 'brayan.pardo@empresa.com',
    role: 'developer',
    status: 'active',
    joinDate: new Date('2021-12-02'),
    salary: 82000,
    department: 'Engineering',
  },
  {
    id: 40,
    name: 'Brayan Pardo',
    email: 'brayan.pardo@empresa.com',
    role: 'developer',
    status: 'active',
    joinDate: new Date('2021-12-02'),
    salary: 82000,
    department: 'Engineering',
  },
  {
    id: 40,
    name: 'Brayan Pardo',
    email: 'brayan.pardo@empresa.com',
    role: 'developer',
    status: 'active',
    joinDate: new Date('2021-12-02'),
    salary: 82000,
    department: 'Engineering',
  },
  {
    id: 40,
    name: 'Brayan Pardo',
    email: 'brayan.pardo@empresa.com',
    role: 'developer',
    status: 'active',
    joinDate: new Date('2021-12-02'),
    salary: 82000,
    department: 'Engineering',
  },
  {
    id: 40,
    name: 'Brayan Pardo',
    email: 'brayan.pardo@empresa.com',
    role: 'developer',
    status: 'active',
    joinDate: new Date('2021-12-02'),
    salary: 82000,
    department: 'Engineering',
  },
  {
    id: 40,
    name: 'Brayan Pardo',
    email: 'brayan.pardo@empresa.com',
    role: 'developer',
    status: 'active',
    joinDate: new Date('2021-12-02'),
    salary: 82000,
    department: 'Engineering',
  },
  {
    id: 40,
    name: 'Brayan Pardo',
    email: 'brayan.pardo@empresa.com',
    role: 'developer',
    status: 'active',
    joinDate: new Date('2021-12-02'),
    salary: 82000,
    department: 'Engineering',
  },
  {
    id: 40,
    name: 'Brayan Pardo',
    email: 'brayan.pardo@empresa.com',
    role: 'developer',
    status: 'active',
    joinDate: new Date('2021-12-02'),
    salary: 82000,
    department: 'Engineering',
  },
  {
    id: 40,
    name: 'Brayan Pardo',
    email: 'brayan.pardo@empresa.com',
    role: 'developer',
    status: 'active',
    joinDate: new Date('2021-12-02'),
    salary: 82000,
    department: 'Engineering',
  },
  {
    id: 40,
    name: 'Brayan Pardo',
    email: 'brayan.pardo@empresa.com',
    role: 'developer',
    status: 'active',
    joinDate: new Date('2021-12-02'),
    salary: 82000,
    department: 'Engineering',
  },
  {
    id: 40,
    name: 'Brayan Pardo',
    email: 'brayan.pardo@empresa.com',
    role: 'developer',
    status: 'active',
    joinDate: new Date('2021-12-02'),
    salary: 82000,
    department: 'Engineering',
  },
  {
    id: 40,
    name: 'Brayan Pardo',
    email: 'brayan.pardo@empresa.com',
    role: 'developer',
    status: 'active',
    joinDate: new Date('2021-12-02'),
    salary: 82000,
    department: 'Engineering',
  },
  {
    id: 40,
    name: 'Brayan Pardo',
    email: 'brayan.pardo@empresa.com',
    role: 'developer',
    status: 'active',
    joinDate: new Date('2021-12-02'),
    salary: 82000,
    department: 'Engineering',
  },
  {
    id: 40,
    name: 'Brayan Pardo',
    email: 'brayan.pardo@empresa.com',
    role: 'developer',
    status: 'active',
    joinDate: new Date('2021-12-02'),
    salary: 82000,
    department: 'Engineering',
  },
  {
    id: 40,
    name: 'Brayan Pardo',
    email: 'brayan.pardo@empresa.com',
    role: 'developer',
    status: 'active',
    joinDate: new Date('2021-12-02'),
    salary: 82000,
    department: 'Engineering',
  },
];
