export const USUARIOS_TEST_ONE: any = [
  {
    id: 1,
    name: 'Juan Pérez',
    email: 'juan.perez@empresa.com',
    role: 'developer',
    status: 'active',
    joinDate: new Date('2023-01-15'),
    salary: 75000,
    department: 'Engineering',
  },
  {
    id: 2,
    name: 'María García',
    email: 'maria.garcia@empresa.com',
    role: 'designer',
    status: 'active',
    joinDate: new Date('2023-03-20'),
    salary: 68000,
    department: 'Design',
  },
  {
    id: 3,
    name: 'Carlos López',
    email: 'carlos.lopez@empresa.com',
    role: 'manager',
    status: 'active',
    joinDate: new Date('2022-11-10'),
    salary: 95000,
    department: 'Management',
  },
  {
    id: 4,
    name: 'Ana Martínez',
    email: 'ana.martinez@empresa.com',
    role: 'developer',
    status: 'pending',
    joinDate: new Date('2024-01-05'),
    salary: 72000,
    department: 'Engineering',
  },
  {
    id: 5,
    name: 'Luis Rodríguez',
    email: 'luis.rodriguez@empresa.com',
    role: 'admin',
    status: 'inactive',
    joinDate: new Date('2023-07-22'),
    salary: 85000,
    department: 'IT',
  },
  {
    id: 6,
    name: 'Luis Rodríguez',
    email: 'luis.rodriguez@empresa.com',
    role: 'admin',
    status: 'inactive',
    joinDate: new Date('2023-07-22'),
    salary: 85000,
    department: 'IT',
  },
  {
    id: 7,
    name: 'Luis Rodríguez',
    email: 'luis.rodriguez@empresa.com',
    role: 'admin',
    status: 'inactive',
    joinDate: new Date('2023-07-22'),
    salary: 85000,
    department: 'IT',
  },
  {
    id: 8,
    name: 'Luis Rodríguez',
    email: 'luis.rodriguez@empresa.com',
    role: 'admin',
    status: 'inactive',
    joinDate: new Date('2023-07-22'),
    salary: 85000,
    department: 'IT',
  },
  {
    id: 9,
    name: 'Luis Rodríguez',
    email: 'luis.rodriguez@empresa.com',
    role: 'admin',
    status: 'inactive',
    joinDate: new Date('2023-07-22'),
    salary: 85000,
    department: 'IT',
  },
  {
    id: 10,
    name: 'Luis Rodríguez',
    email: 'luis.rodriguez@empresa.com',
    role: 'admin',
    status: 'inactive',
    joinDate: new Date('2023-07-22'),
    salary: 85000,
    department: 'IT',
  },
  {
    id: 11,
    name: 'Luis Rodríguez',
    email: 'luis.rodriguez@empresa.com',
    role: 'admin',
    status: 'inactive',
    joinDate: new Date('2023-07-22'),
    salary: 85000,
    department: 'IT',
  },
];
export const USUARIOS_TEST_TWO: any = [
  {
    id: 11,
    name: 'Luis Rodríguez',
    email: 'luis.rodriguez@empresa.com',
    role: 'admin',
    status: 'inactive',
    joinDate: new Date('2023-07-22'),
    salary: 85000,
    department: 'IT',
  },
  {
    id: 12,
    name: 'Luis Rodríguez',
    email: 'luis.rodriguez@empresa.com',
    role: 'admin',
    status: 'inactive',
    joinDate: new Date('2023-07-22'),
    salary: 85000,
    department: 'IT',
  },
];
